config:
  user_keys_dir: "/etc/edmunds-chef-proxy/keys/users"
  keys:
    readonly_client: "proxyreadonly"
    readonly_key: "/etc/edmunds-chef-proxy/keys/readonly.pem"
    readwrite_client: "proxyreadwrite"
    readwrite_key: "/etc/edmunds-chef-proxy/keys/readwrite.pem"
  notifications: "dvinogradov@edmunds.com"

groups:
  readonly:
    rules: [ { method: "GET", url: ".*"} ]
  hadoop:
    rules: [ { method: "GET", url: ".*"},
             { method: "GET|PUT|POST|DELETE", url: "/environments/hadoop.*"},
             { method: "GET|PUT|POST|DELETE", url: "/roles/hadoop.*"},
             { method: "GET|PUT|POST|DELETE", url: "/cookbooks/hadoop.*"} ]

users:
  dvinogradov:
    groups: [ readonly, hadoop ]
